common: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: googler
  password: googler_password

development:
  <<: *default
  database: googler_development
  
  <<: *default
  database: googler_test 

production:
  <<: *default
  database: googler_production
